# Copyright (c) 2021, Kai Wolf - SW Consulting. All rights reserved.
# For the licensing terms see LICENSE file in the root directory. For the
# list of contributors see the AUTHORS file in the same directory.

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "audio",
    srcs = [
        "PcmUtils.cc",
        "SineGenerator.cc",
    ],
    hdrs = [
        "Dft.h",
        "PcmUtils.h",
        "SineGenerator.h",
    ],
    deps = [
        "//kwctoolkit/base",
    ]
)
